name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: write
  pull-requests: read

jobs:
  docs:
    name: ${{ matrix.pkg.name }} Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - name: GeneralisedFilters
            path: GeneralisedFilters
          - name: SSMProblems
            path: SSMProblems
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build and deploy Documenter.jl docs
        uses: TuringLang/actions/DocsDocumenter@main
        with:
          # Specify the package subdirectory
          subdir: ${{ matrix.pkg.path }}
          # Adjust paths accordingly
          doc-path: ${{ matrix.pkg.path }}/docs
          doc-make-path: ${{ matrix.pkg.path }}/docs/make.jl
          doc-build-path: ${{ matrix.pkg.path }}/docs/build
